// signal.js — Robust rPPG: POS+CHROM auto-select, cascaded Butterworth, adaptive HR
window.Signal=(function(){'use strict';
function bqCoeffs(fc,fs,type){var w0=2*Math.PI*fc/fs,alpha=Math.sin(w0)/(2*0.7071),c=Math.cos(w0),b0,b1,b2;if(type==='low'){b0=(1-c)/2;b1=1-c;b2=(1-c)/2}else{b0=(1+c)/2;b1=-(1+c);b2=(1+c)/2}var a0=1+alpha;return{b:[b0/a0,b1/a0,b2/a0],a:[1,-2*c/a0,(1-alpha)/a0]}}
function bqFwd(s,c){var n=s.length,o=new Float64Array(n),x1=0,x2=0,y1=0,y2=0;for(var i=0;i<n;i++){o[i]=c.b[0]*s[i]+c.b[1]*x1+c.b[2]*x2-c.a[1]*y1-c.a[2]*y2;x2=x1;x1=s[i];y2=y1;y1=o[i]}return o}
function bqRev(s,c){var n=s.length,o=new Float64Array(n),x1=0,x2=0,y1=0,y2=0;for(var i=n-1;i>=0;i--){o[i]=c.b[0]*s[i]+c.b[1]*x1+c.b[2]*x2-c.a[1]*y1-c.a[2]*y2;x2=x1;x1=s[i];y2=y1;y1=o[i]}return o}
function bandpass(sig,fs,lo,hi){if(lo<=0||hi>=fs/2||lo>=hi)return new Float64Array(sig);var hp=bqCoeffs(lo,fs,'high');var s=bqFwd(sig,hp);s=bqRev(s,hp);s=bqFwd(s,hp);s=bqRev(s,hp);var lp=bqCoeffs(hi,fs,'low');s=bqFwd(s,lp);s=bqRev(s,lp);s=bqFwd(s,lp);return bqRev(s,lp)}
function detrend(sig){var n=sig.length,sx=0,sy=0,sxx=0,sxy=0;for(var i=0;i<n;i++){sx+=i;sy+=sig[i];sxx+=i*i;sxy+=i*sig[i]}var det=n*sxx-sx*sx;if(Math.abs(det)<1e-12)return sig;var m=(n*sxy-sx*sy)/det,b2=(sy-m*sx)/n;var o=new Float64Array(n);for(var i=0;i<n;i++)o[i]=sig[i]-(m*i+b2);return o}
function pos(rgb,fs){fs=fs||30;var n=rgb.length;if(n<fs*2)return new Float64Array(n);var ws=Math.round(fs*1.6),step=Math.max(1,Math.round(ws/6)),bvp=new Float64Array(n),wt=new Float64Array(n);for(var st=0;st<n-ws;st+=step){var mr=0,mg=0,mb=0;for(var i=st;i<st+ws;i++){mr+=rgb[i][0];mg+=rgb[i][1];mb+=rgb[i][2]}mr/=ws;mg/=ws;mb/=ws;if(mr<5||mg<5||mb<5)continue;var s1=new Float64Array(ws),s2=new Float64Array(ws);for(var i=0;i<ws;i++){var rn=rgb[st+i][0]/mr,gn=rgb[st+i][1]/mg,bn=rgb[st+i][2]/mb;s1[i]=gn-bn;s2[i]=-2*rn+gn+bn}var m1=0,m2=0;for(var i=0;i<ws;i++){m1+=s1[i];m2+=s2[i]}m1/=ws;m2/=ws;var v1=0,v2=0;for(var i=0;i<ws;i++){v1+=(s1[i]-m1)*(s1[i]-m1);v2+=(s2[i]-m2)*(s2[i]-m2)}var std1=Math.sqrt(v1/ws),std2=Math.sqrt(v2/ws),alpha=std2>1e-10?std1/std2:1;for(var i=0;i<ws;i++){var w=.5*(1-Math.cos(2*Math.PI*i/(ws-1)));bvp[st+i]+=(s1[i]+alpha*s2[i])*w;wt[st+i]+=w}}for(var i=0;i<n;i++)if(wt[i]>0)bvp[i]/=wt[i];return bvp}
function chrom(rgb,fs){fs=fs||30;var n=rgb.length,ws=Math.round(fs*1.6),step=Math.max(1,Math.round(ws/6)),bvp=new Float64Array(n),wt=new Float64Array(n);for(var st=0;st<n-ws;st+=step){var mr=0,mg=0,mb=0;for(var i=st;i<st+ws;i++){mr+=rgb[i][0];mg+=rgb[i][1];mb+=rgb[i][2]}mr/=ws;mg/=ws;mb/=ws;if(mr<5||mg<5||mb<5)continue;var xs=new Float64Array(ws),ys=new Float64Array(ws);for(var i=0;i<ws;i++){var rn=rgb[st+i][0]/mr,gn=rgb[st+i][1]/mg,bn=rgb[st+i][2]/mb;xs[i]=3*rn-2*gn;ys[i]=1.5*rn+gn-1.5*bn}var sx=0,sy=0;for(var i=0;i<ws;i++){sx+=xs[i]*xs[i];sy+=ys[i]*ys[i]}var al=sy>1e-10?Math.sqrt(sx/sy):1;for(var i=0;i<ws;i++){var w=.5*(1-Math.cos(2*Math.PI*i/(ws-1)));bvp[st+i]+=(xs[i]-al*ys[i])*w;wt[st+i]+=w}}for(var i=0;i<n;i++)if(wt[i]>0)bvp[i]/=wt[i];return bvp}
function fft(re,im){var n=re.length;for(var i=1,j=0;i<n;i++){var b=n>>1;for(;j&b;b>>=1)j^=b;j^=b;if(i<j){var t=re[i];re[i]=re[j];re[j]=t;t=im[i];im[i]=im[j];im[j]=t}}for(var len=2;len<=n;len*=2){var a=-2*Math.PI/len,wR=Math.cos(a),wI=Math.sin(a);for(var i=0;i<n;i+=len){var cR=1,cI=0;for(var j=0;j<len/2;j++){var uR=re[i+j],uI=im[i+j],vR=re[i+j+len/2]*cR-im[i+j+len/2]*cI,vI=re[i+j+len/2]*cI+im[i+j+len/2]*cR;re[i+j]=uR+vR;im[i+j]=uI+vI;re[i+j+len/2]=uR-vR;im[i+j+len/2]=uI-vI;var nR=cR*wR-cI*wI;cI=cR*wI+cI*wR;cR=nR}}}}
function powerSpectrum(sig,fs){var n=1;while(n<sig.length)n*=2;var re=new Float64Array(n),im=new Float64Array(n);for(var i=0;i<sig.length;i++)re[i]=sig[i]*(.5-.5*Math.cos(2*Math.PI*i/(sig.length-1)));fft(re,im);var f=[],p=[];for(var i=0;i<n/2;i++){f.push(i*fs/n);p.push(Math.sqrt(re[i]*re[i]+im[i]*im[i]))}return{freqs:f,power:p}}
function findHR(bvp,fs){var sp=powerSpectrum(bvp,fs),mx=0,hf=1.2;for(var i=0;i<sp.freqs.length;i++)if(sp.freqs[i]>=.7&&sp.freqs[i]<=3.5&&sp.power[i]>mx){mx=sp.power[i];hf=sp.freqs[i]}return{hr:hf*60,freq:hf,spec:sp}}
function extractBVP(rgb,fs){fs=fs||30;if(rgb.length<fs*3)return null;var bp=bandpass(detrend(pos(rgb,fs)),fs,.7,4),bc=bandpass(detrend(chrom(rgb,fs)),fs,.7,4);var hp=findHR(bp,fs),hc=findHR(bc,fs);var sp=hp.spec,sc2=hc.spec,snrP=0,snrC=0,sum1=0,sum2=0,cnt=0;for(var i=0;i<sp.freqs.length;i++)if(sp.freqs[i]>=.7&&sp.freqs[i]<=3.5){sum1+=sp.power[i];sum2+=sc2.power[i];cnt++}var mp=sum1/cnt,mc=sum2/cnt;for(var i=0;i<sp.freqs.length;i++){if(Math.abs(sp.freqs[i]-hp.freq)<.15)snrP=sp.power[i]/(mp+1e-10);if(Math.abs(sc2.freqs[i]-hc.freq)<.15)snrC=sc2.power[i]/(mc+1e-10)}var use=snrP>=snrC;return{bvp:use?bp:bc,hr:(use?hp:hc).hr,hrFreq:(use?hp:hc).freq,spec:(use?hp:hc).spec,snr:Math.max(snrP,snrC),method:use?'POS':'CHROM'}}
function findPeaks(sig,md,mp){var pk=[];for(var i=1;i<sig.length-1;i++){if(sig[i]>sig[i-1]&&sig[i]>=sig[i+1]){var lm=sig[i],rm=sig[i];for(var j=i-1;j>=Math.max(0,i-md*2);j--)lm=Math.min(lm,sig[j]);for(var j=i+1;j<=Math.min(sig.length-1,i+md*2);j++)rm=Math.min(rm,sig[j]);var pr=sig[i]-Math.max(lm,rm);if(pr>=mp){if(pk.length===0||i-pk[pk.length-1]>=md)pk.push(i);else if(sig[i]>sig[pk[pk.length-1]])pk[pk.length-1]=i}}}return pk}
function extractFeatures(bvpR,fs,profile){if(!bvpR||!bvpR.bvp)return null;var fl=bvpR.bvp;fs=fs||30;var md=Math.max(Math.floor(fs*.35),3),mn=-Infinity,mx=Infinity;for(var i=0;i<fl.length;i++){if(fl[i]>mn)mn=fl[i];if(fl[i]<mx)mx=fl[i]}var rng=mn-mx,pm=Math.max(rng*.08,.0001);var pks=findPeaks(fl,md,pm);if(pks.length<3)return null;var ib=[];for(var i=1;i<pks.length;i++){var v=(pks[i]-pks[i-1])/fs;if(v>.3&&v<2)ib.push(v)}if(ib.length<2)return null;var mi=0;for(var i=0;i<ib.length;i++)mi+=ib[i];mi/=ib.length;var hr=60/mi;if(hr<40||hr>200)hr=bvpR.hr;if(hr<40||hr>200)return null;var sd=0;for(var i=0;i<ib.length;i++)sd+=(ib[i]-mi)*(ib[i]-mi);sd=Math.sqrt(sd/ib.length);var rm=0;for(var i=1;i<ib.length;i++)rm+=(ib[i]-ib[i-1])*(ib[i]-ib[i-1]);rm=Math.sqrt(rm/Math.max(1,ib.length-1));var pn=0;if(ib.length>1){var nn=0;for(var i=1;i<ib.length;i++)if(Math.abs(ib[i]-ib[i-1])>.05)nn++;pn=nn/ib.length}
var tr=[];for(var i=0;i<pks.length-1;i++){var mv=Infinity,mi2=pks[i];for(var j=pks[i];j<pks[i+1];j++)if(fl[j]<mv){mv=fl[j];mi2=j}tr.push(mi2)}var bts=[];for(var i=0;i<tr.length-1;i++){var bl=tr[i+1]-tr[i];if(bl>Math.max(fs*.3,5)&&bl<fs*2){var bt=[];for(var j=tr[i];j<tr[i+1];j++)bt.push(fl[j]);bts.push(bt)}}if(bts.length<2)return null;var al=0;for(var i=0;i<bts.length;i++)al+=bts[i].length;al=Math.round(al/bts.length);if(al<6)return null;var av=new Float64Array(al);for(var b=0;b<bts.length;b++)for(var i=0;i<al;i++){var si=i*(bts[b].length-1)/(al-1),lo=Math.floor(si),hi2=Math.min(lo+1,bts[b].length-1),fr=si-lo;av[i]+=(bts[b][lo]*(1-fr)+bts[b][hi2]*fr)/bts.length}
var bmn=Infinity,bmx=-Infinity;for(var i=0;i<al;i++){if(av[i]<bmn)bmn=av[i];if(av[i]>bmx)bmx=av[i]}var br=bmx-bmn;if(br<1e-10)return null;for(var i=0;i<al;i++)av[i]=(av[i]-bmn)/br;
var pk=0,pa=av[0];for(var i=1;i<al;i++)if(av[i]>pa){pa=av[i];pk=i}if(pa===0||pk===0)return null;var ct=pk/fs,ms=0;for(var i=1;i<=pk;i++){var s=(av[i]-av[i-1])*fs;if(s>ms)ms=s}
function pw(lv){var am=pa*lv,s2=0,e2=al-1;for(var i=0;i<pk;i++)if(av[i]>=am){s2=i;break}for(var i=al-1;i>pk;i--)if(av[i]>=am){e2=i;break}return(e2-s2)/fs}
var p10=pw(.1),p25=pw(.25),p50=pw(.5),p75=pw(.75),p90=pw(.9);var sa=0,da=0;for(var i=0;i<=pk;i++)sa+=Math.abs(av[i]);for(var i=pk+1;i<al;i++)da+=Math.abs(av[i]);var ar=sa/(sa+da)||.5;var se=Math.min(pk+Math.floor(al*.45),al),di=pk,ri=.5;if(se>pk+1){var mdic=Infinity;for(var i=pk+1;i<se;i++)if(av[i]<mdic){mdic=av[i];di=i}ri=av[di]/pa}var ai=0;if(di<al-2&&pa>0){var mxp=-Infinity;for(var i=di+1;i<al;i++)if(av[i]>mxp)mxp=av[i];ai=mxp/pa}
var ab=0,ac=0,ad=0;if(al>8){var d1=new Float64Array(al),d2=new Float64Array(al);for(var i=1;i<al-1;i++)d1[i]=(av[i+1]-av[i-1])/2;for(var i=1;i<al-1;i++)d2[i]=(d1[i+1]-d1[i-1])/2;var ax=0,avl=d2[0];for(var i=1;i<=pk;i++)if(d2[i]>avl){avl=d2[i];ax=i}if(Math.abs(avl)>1e-12){var bv=Infinity,bi=ax+1;for(var i=ax+1;i<=pk;i++)if(d2[i]<bv){bv=d2[i];bi=i}ab=bv/avl;var cv=-Infinity,ci=bi+1;for(var i=bi+1;i<se;i++)if(d2[i]>cv){cv=d2[i];ci=i}ac=isFinite(cv)?cv/avl:0;var dv=Infinity;for(var i=ci+1;i<al;i++)if(d2[i]<dv)dv=d2[i];ad=isFinite(dv)?dv/avl:0}}
var dc=0;if(di<al-2)dc=(av[di]-av[al-1])/((al-di)/fs);var pp=pa-av[0];for(var i=1;i<al;i++)if(av[i]<av[0])pp=pa-av[i];var bm=0;for(var i=0;i<al;i++)bm+=av[i];bm/=al;var m2=0,m3=0,m4=0;for(var i=0;i<al;i++){var d=av[i]-bm;m2+=d*d;m3+=d*d*d;m4+=d*d*d*d}m2/=al;m3/=al;m4/=al;var bsk=m2>0?m3/Math.pow(m2,1.5):0,bkt=m2>0?m4/(m2*m2)-3:0;
var siv=0,h=(profile&&profile.height)?profile.height:0;if(h>0&&di>pk){var dt=(di-pk)/fs;if(dt>0)siv=(h/100)/dt}
var age=(profile&&profile.age)?profile.age:50,bmi2=(profile&&profile.bmi)?profile.bmi:25,gen=(profile&&profile.gender!==null&&profile.gender!==undefined)?profile.gender:0;
var R=function(v,d){return Math.round(v*Math.pow(10,d))/Math.pow(10,d)};
return{hr:R(hr,1),meanIBI:R(mi,4),sdnn:R(sd,5),rmssd:R(rm,5),pnn50:R(pn,4),crestTime:R(ct,4),maxSlope:R(ms,3),pw10:R(p10,4),pw25:R(p25,4),pw50:R(p50,4),pw75:R(p75,4),pw90:R(p90,4),areaRatio:R(ar,4),reflectionIndex:R(ri,4),augmentationIndex:R(ai,4),apgBARatio:R(ab,4),apgCARatio:R(ac,4),apgDARatio:R(ad,4),numBeats:bts.length,decayRate:R(dc,4),ppProxy:R(pp,4),age:age,bmi:bmi2,gender:gen,lfHfRatio:1,beatSkew:R(bsk,4),beatKurt:R(bkt,4),stiffnessIndex:R(siv,2),_avgBeat:av,_peaks:pks,_filtered:fl,_snr:bvpR.snr,_method:bvpR.method}}
return{pos:pos,chrom:chrom,extractBVP:extractBVP,bandpass:bandpass,detrend:detrend,powerSpectrum:powerSpectrum,findPeaks:findPeaks,findHR:findHR,extractFeatures:extractFeatures}})();
